select * from customer limit 5;

--1 What is the total revenue generated by male vs. female customers?:
select gender,
SUM(purchase_amount) as revenue
from customer
GROUP BY gender;
-- Males purchased more items.

--2 Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
WHERE discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);
-- 839 customers used discount, but still spent more than average.

--3 Which are the top 5 products with the highest average review rating?:
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer 
GROUP BY item_purchased
ORDER BY AVG(review_rating) desc
limit 5;
-- Gloves had the highest review rating at 3.86

--4 Compare the average Purchase Amounts between Standard and Express Shipping:
select shipping_type, ROUND(AVG(purchase_amount::numeric),2) as "Average Purchase Amount"
from customer
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) desc
-- 2 day shipping had the highest avg purchase amount.
-- standard shipping had the lowest purchase amount.

--5 Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status, COUNT(customer_id) as "Total Customers", 
ROUND(AVG(purchase_amount::numeric),2) as "Average Purchase Amount",
COUNT(purchase_amount) as "Total Revenue"
from customer
GROUP BY subscription_status
ORDER BY "Total Revenue", "Average Purchase Amount" desc
-- customers with no subscription spend more by average and total
-- there are more customers with no subscription status

--6 Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, 
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*),2) as discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5
-- Hat had the highest percentage of purchase with discount applied.

--7 Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
from customer
)
select customer_segment, COUNT(*) as "Number of Customers"
from customer_type
GROUP BY customer_segment
-- There is about 3000 loyal customers, 701 Returning and 83 New

--8 What are the top 3 most purchased products within each category?:
with item_counts as (
select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by COUNT(customer_id) DESC) as item_rank
from customer
GROUP BY category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--9 Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, COUNT(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
GROUP BY subscription_status

--10 What is the revenue contribution of each age group?:
select age_group, SUM(purchase_amount) as total_revenue
from customer
GROUP BY age_group
ORDER BY total_revenue DESC
-- Young Adult has more in revenue, while Seniors have the least.
